databases:
  - name: teste-db
    databaseName: teste
    user: userdb

services:
  - type: web
    name: teste3
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn teste3.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teste-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4